<?php
/**
 * Copyright © 2019 Wyomind. All rights reserved.
 * See LICENSE.txt for license details.
 */
/** @var \Wyomind\DataFeedManager\Block\Adminhtml\Feeds\Edit\Tab\Filters $block */
?>
<!-- Data feed filters template -->
<div class="entry-edit form-inline">
    <fieldset id="type-ids-selector" class="fieldset ">
        <legend class="legend">
            <span><?php /* @noEscape */ echo __('Product Type'); ?></span>
            <span class="select-all"><?php /* @noEscape */ echo __('Select all'); ?></span>
            <span class="unselect-all"><?php /* @noEscape */ echo __('Unselect all'); ?></span>
        </legend>
        <br/>
        <div>
            <?php foreach($this->getProductTypes() as $name => $label): ?>
                <div class="node">
                    <div class='cat-box'>
                        <input class="filter_product_type" type='checkbox' id='type_id_<?=$name?>' identifier='<?=$name?>'/>
                        <label for="type_id_<?=$name?>"><?php /* @noEscape */ echo __(str_replace(' Product', '', $label)); ?></label>
                    </div>
                </div>
            <?php endforeach; ?>
            <input id="type_ids" name="type_ids" value='<?php /* @noEscape */ echo $block->getDFMTypeIds(); ?>' class="input-text required debug" type="hidden">
        </div>
    </fieldset>
    <fieldset id="attribute-sets-selector" class="fieldset ">
        <legend class="legend">
            <span><?php /* @noEscape */ echo __('Attribute Set'); ?></span>
            <span class="select-all"><?php /* @noEscape */ echo __('Select all'); ?></span>
            <span class="unselect-all"><?php /* @noEscape */ echo __('Unselect all'); ?></span>
        </legend>
        <br/>
        <div>
            <?php $attributeSets = $block->getAttributeSets(); ?>
            <?php foreach ($attributeSets as $set) : ?>
                <div class="node">
                    <div class="cat-box">
                        <input type="checkbox" class="filter_attribute_set" id='attribute_set_<?php /* @noEscape */ echo $set->getAttributeSetId(); ?>'
                               identifier='<?php /* @noEscape */ echo $set->getAttributeSetId(); ?>'/>
                        <label for="attribute_set_<?php /* @noEscape */ echo $set->getAttributeSetId(); ?>">
                            <?php /* @noEscape */ echo $set->getAttributeSetName(); ?>
                        </label>
                    </div>
                </div>
            <?php endforeach; ?>
            <input id="attribute_sets" name="attribute_sets" class="input-text required debug" type="hidden"
                   value='<?php /* @noEscape */ echo $block->getDFMAttributeSets(); ?>'>
        </div>
    </fieldset>
    <fieldset id="visibility-selector" class="fieldset">
        <legend class="legend">
            <span><?php /* @noEscape */ echo __('Product Visibility'); ?></span>
            <span class="select-all"><?php /* @noEscape */ echo __('Select all'); ?></span>
            <span class="unselect-all"><?php /* @noEscape */ echo __('Unselect all'); ?></span>
        </legend>
        <br/>
        <div>
            <div class="node">
                <div class="cat-box">
                    <input class="filter_visibility" type="checkbox" id="visibility_1" identifier="1" />
                    <label for="visibility_1"><?php /* @noEscape */ echo __('Not Visible Individually'); ?></label>
                </div>
            </div>
            <div class="node">
                <div class="cat-box">
                    <input class="filter_visibility" type="checkbox" id="visibility_2" identifier="2" />
                    <label for="visibility_2"><?php /* @noEscape */ echo __('Catalog'); ?></label>
                </div>
            </div>
            <div class="node">
                <div class="cat-box">
                    <input class="filter_visibility" type="checkbox" id="visibility_3" identifier="3" />
                    <label for="visibility_3"><?php /* @noEscape */ echo __('Search'); ?></label>
                </div>
            </div>
            <div class="node">
                <div class="cat-box">
                    <input class="filter_visibility" type="checkbox" id="visibility_4" identifier="4" />
                    <label for="visibility_4"><?php /* @noEscape */ echo __('Catalog, Search'); ?></label>
                </div>
            </div>
            <input id="visibilities" name="visibilities" class="input-text required debug" type="hidden"
                   value='<?php /* @noEscape */ echo $block->getDFMVisibilities(); ?>'>
        </div>
    </fieldset>
    <fieldset id="attributes-selector" class="fieldset ">
        <legend class="legend">
            <span><?php /* @noEscape */ echo __('Advanced filters'); ?></span>
        </legend>
        <br/>
        <div>
            <?php $selectOutput = $block->getSelectHtml(); ?>
            <?php $nbFilters = $block->getNbFilters(); ?>
            <?php for ($x = 0; $x < $nbFilters; $x++) : ?>
                <div class="node advanced_filters" id='node_<?php /* @noEscape */ echo $x; ?>'>
                    <table class="cat-box one-value">
                        <tr>
                            <td>
                                <input class="checked-attribute" type="checkbox" id='attribute_<?php /* @noEscape */ echo $x; ?>'
                                       identifier='<?php /* @noEscape */ echo $x; ?>'/>
                            </td>
                            <?php $display = (!$block->getFiltersSql()) ? 'none' : ''; ?>
                            <td>
                                <?php if ($x > 0) : ?>
                                    <select style="display:<?php /* @noEscape */ echo $display; ?>;" disabled="disabled" class="statement-attribute" id='statement_attribute_<?php /* @noEscape */ echo $x; ?>'>
                                        <option value="AND">AND</option>
                                        <option value="OR">OR</option>
                                    </select>
                                <?php else : ?>
                                    <input type="text" id='statement_attribute_<?php /* @noEscape */ echo $x; ?>' value="" class="statement-attribute" style=" display:<?php /* @noEscape */ echo $display; ?>;"/>
                                <?php endif; ?>
                            </td>
                            <td>
                                <select style="" disabled="disabled" class="name-attribute"
                                        id='name_attribute_<?php /* @noEscape */ echo $x; ?>' identifier="<?php /* @noEscape */ echo $x; ?>">
                                    <?php /* @noEscape */ echo $selectOutput; ?>
                                </select>
                            </td>
                            <td>
                                <select disabled="disabled" class="condition-attribute"
                                        id='condition_attribute_<?php /* @noEscape */ echo $x; ?>' identifier="<?php /* @noEscape */ echo $x; ?>">
                                    <option value="eq"><?php /* @noEscape */ echo __('='); ?></option>
                                    <option value="gt"><?php /* @noEscape */ echo __('>'); ?></option>
                                    <option value="lt"><?php /* @noEscape */ echo __('<'); ?></option>
                                    <option value="gteq"><?php /* @noEscape */ echo __('&ge;'); ?></option>
                                    <option value="lteq"><?php /* @noEscape */ echo __('&le;'); ?></option>
                                    <option value="neq"><?php /* @noEscape */ echo __('&ne;'); ?></option>
                                    <option value="like"><?php /* @noEscape */ echo __('like'); ?></option>
                                    <option value="nlike"><?php /* @noEscape */ echo __('not like'); ?></option>
                                    <option value="null"><?php /* @noEscape */ echo __('is null'); ?></option>
                                    <option value="notnull"><?php /* @noEscape */ echo __('is not null'); ?></option>
                                    <option value="in"><?php /* @noEscape */ echo __('in'); ?></option>
                                    <option value="nin"><?php /* @noEscape */ echo __('not in'); ?></option>
                                </select>
                            </td>
                            <td>
                                <select disabled="disabled" class="pre-value-attribute" multiple="multiple" size="5"
                                        id="pre_value_attribute_<?php /* @noEscape */ echo $x; ?>"
                                        identifier="<?php /* @noEscape */ echo $x; ?>"></select>
                                <input disabled="disabled" type="text"
                                       class="value-attribute <?php /* @noEscape */ echo $block->getFiltersSql() ? "advanced" : ""; ?>"
                                       id="value_attribute_<?php /* @noEscape */ echo $x; ?>"/>
                            </td>
                        </tr>
                    </table>
                </div>
            <?php endfor; ?>
        </div>
    </fieldset>
</div>
<script>
    require(["jquery", "dfm_filters"], function ($, filters) {
        'use strict';
        filters.attributeCodes = <?php /* @noEscape */ echo $block->getJsData(); ?>;
        filters.attributeCodes['is_in_stock'] = [{"label": "Yes", "value": 1}, {"label": "No", "value": 0}];
        filters.attributeCodes['qty'] = [];
        filters.attributeCodes['entity_id'] = [];

        /* select product types */
        $(document).on("click", ".filter_product_type", function (evt) {
            var elt = $(this);
            elt.parent().toggleClass('selected');
            filters.updateProductTypes();
        });

        filters.loadProductTypes();

        /* select attribute sets */
        $(document).on("click", ".filter_attribute_set", function (evt) {
            var elt = $(this);
            elt.parent().toggleClass('selected');
            filters.updateAttributeSets();
        });

        filters.loadAttributeSets();

        /* select product visibilities */
        $(document).on("click", ".filter_visibility", function (evt) {
            var elt = $(this);
            elt.parent().toggleClass('selected');
            filters.updateProductVisibilities();
        });

        filters.loadProductVisibilities();

        /* un/select all */
        $(document).on("click", ".select-all", function (evt) {
            var elt = $(this);
            filters.selectAll(elt);
        });

        $(document).on("click", ".unselect-all", function (evt) {
            var elt = $(this);
            filters.unselectAll(elt);
        });

        filters.updateUnSelectLinks();

        /* select advanced filters */
        // change attribute select 
        $(document).on('change', '.name-attribute,.condition-attribute', function (evt) {
            var id = $(this).attr('identifier');
            var attribute_code = $('#name_attribute_' + id).val();
            filters.updateRow(id, attribute_code);
        });

        $(document).on('change', '.checked-attribute,.statement-attribute,.name-attribute,.condition-attribute,.value-attribute,.pre-value-attribute', function (evt) {
            filters.updateAdvancedFilters();
        });

        filters.loadAdvancedFilters();
    });
</script>