<script>

    /* for code mirror syntactic coloration */
    var DataFeedManager = {};

    var Utils = {
    sampleUrl : '<?= /* @noEscape */ $block->getUrl("*/*/sample"); ?>',
    libraryUrl : '<?= /* @noEscape */ $block->getUrl("*/*/library"); ?>',
    librarySampleUrl : '<?= /* @noEscape */ $block->getUrl("*/*/librarysample"); ?>',
    categoriesUrl : '<?= /* @noEscape */ $block->getUrl("*/*/categories"); ?>'
}
</script>